/*
 * This source file was generated by the Gradle 'init' task
 */
package qa_makemytrip;

import static org.testng.Assert.assertNotNull;

import java.io.IOException;
import java.net.MalformedURLException;

import org.testng.annotations.Test;

public class AppTest {
    @Test public void getGreeting() throws InterruptedException, IOException {
        Testcases tests = new Testcases(); 
        tests.Testcase01();
        tests.Testcase02();
        tests.Testcase03();

        tests.endTest(); //End your test cases
     
    }

    public static void main(String[] args) throws InterruptedException, MalformedURLException {
        new App().getGreeting();
    }
    
}
